### PR TITLE
feat: Improve search context feature

### PR DESCRIPTION
**Pull request by aericson**
This PR builds on the feature built on #279. It improves the UI and add a new option `useAllContextsWithNoSearchContext`.

1. `useAllContextsWithNoSearchContext`
Adds an option that is off by default. The indexes from all contexts will also be present on the default index. This is to allow searching on every index. Using this option together with `searchContextByPaths` allows context and global searches.
2. Improvements to the the context UI by:
   - Displaying an indicator on the search bar when the using a specific context
       Screenshot 2023-02-10 at 13 48 43
   - Add a select to search by context on the search page
        Screenshot 2023-02-10 at 13 48 15

The following new strings are added and will need to be added to the translation files:
- `theme.SearchBar.searchInContext`
- `theme.SearchPage.searchContext.everywhere`

### CODE REVIEW

**Comment by aericson** [comment]
@weareoutman can you take a look when you have some spare time? 😄

**Comment by weareoutman** [comment]
@aericson Thanks for you contribution, this seems great!

However, I got very busy these weeks, I'll try to look into it later.

**Comment by aericson** [comment]
> @aericson Thanks for you contribution, this seems great!
> 
> However, I got very busy these weeks, I'll try to look into it later.

Take your time, just wanted to get it in your radar in case you haven't seen it.

**Comment by weareoutman** [comment]
Thanks again, release in 0.34.0

**Pull request merged**
