### PR TITLE
Fixed search link when update to Docusaurus 3.4.0

### PR DESCRIPTION
**Pull request by anonid-top**
Fix both search page and search bar with footer link to search page - AnonID.TOP

### CODE REVIEW

**Comment by weareoutman** [comment]
Hi thanks for finding out what's wrong with issue #408 , but we'd better make the `h` in the search index file to be trimmed instead, to save network transfer size when searching on the page.

That's: https://github.com/easyops-cn/docusaurus-search-local/blob/c5b1c299d5209a1d15663697c34f7886ff59706f/docusaurus-search-local/src/server/utils/parseDocument.ts#L42

**Comment by anonid-top** [comment]
> Hi thanks for finding out what's wrong with issue #408 , but we'd better make the `h` in the search index file to be trimmed instead, to save network transfer size when searching on the page.
> 
> That's:
> 
> https://github.com/easyops-cn/docusaurus-search-local/blob/c5b1c299d5209a1d15663697c34f7886ff59706f/docusaurus-search-local/src/server/utils/parseDocument.ts#L42

It's okay, it took me all night to understand how your code works, figure out how to get rid of the redundancy in the ```h``` value, and that's the best I could find and do. It's great that you have a better and more optimal solution. Thank you for your solution.

**Comment by weareoutman** [comment]
Yes, the codebase is quite complex. I'll try to do the fix based on your PR, since I have some other considerations about this fix.

**Comment by anonid-top** [comment]
> Yes, the codebase is quite complex. I'll try to do the fix based on your PR, since I have some other considerations about this fix.

Okey, if we don't use file link in ```h``` value, remove it in ```h``` is best choise for search performance

**Review by weareoutman — APPROVED** [review]

**Pull request merged**
