### PR TITLE
feat(SearchBar): add shortcut (cmd/ctrl + K) support

### PR DESCRIPTION
**Pull request by ksarlou**
This PR fixes the issue: https://github.com/easyops-cn/docusaurus-search-local/issues/110#issue-998094108

### CODE REVIEW

**Comment by madmath** [comment]
Very nice! What's the process to get this merged?

**Comment by weareoutman** [comment]
Thanks for your work and sorry for the late response. I got very little spare time to maintain this project recently. But I'll try reviewing this PR later this week.

**Comment by ksarlou** [comment]
Hello! Thanks for your comments! Should I make any more changes?

**Comment by weareoutman** [comment]
Hi @ksarlou Thanks for your contribution! And sorry again for being late. And I just made some refining based on your commit:

- Fix dark mode colors and put the hint inside input box.
- Fix build errors in production mode by using `ExecutionEnvironment.canUseDOM`.
- Use `navigator.userAgentData.platform` instead of `navigator.platform` which is deprecated.
- Simplify event listening.

**Review by weareoutman — APPROVED** [review]

**Comment by weareoutman** [comment]
Hi guys, this is just released in v0.21.0.

**Pull request merged**
